config/routes.rb
Rails.application.routes.draw do
  get 'resources/new'
  get 'resources/edit'
  get 'cards/new'
  get 'cards/edit'
  devise_for :users

  root to: 'passthrough#index'

  get 'home', to: 'pages#home'

  resources :curriculums, only:[:show, :index] do
    resources :decks, only:[:index, :edit, :update, :new, :create] do
      resources :cards, only:[:edit, :update, :new, :create, :index, :show]
      resources :resources, only: [:new, :create, :edit, :update]
    end
  end

  resources :users, only: [] do
    member do
      get 'dashboard'
      get 'takedeck'
      get 'decksummary'
    end
  end
  resources :attempts, only: [:create]

  resources :sections, only: :show do
    resources :decks, only: :show do
      resources :students, only: :show
        resources :users, only: [] do
          member do
            get 'deck_results'
          end
        end
    end
  end

  get 'feed', to: 'users#feed'

  resources :todo_items, only: [:create, :index] do
    member do
      get 'mark_complete'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :first_name, :last_name, :email, presence: true
  validates :email, uniqueness: true

  has_many :registrations
  has_many :sections, through: :registrations
  has_many :attempts
  has_many :curriculums, -> { where is_teacher: true }
  has_many :feed_events, dependent: :destroy
  has_many :todo_items, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  def feed
    feed_events.order('created_at DESC')
  end

  def deck_attempts(deck)
    self.attempts.select { |attempt| attempt.card.deck == deck }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:dashboard, :takedeck, :decksummary, :deck_results]

  def dashboard
    authorize @user
    @sections = @user.sections
    @curriculums = @sections.each_with_object([]) do |section, array|
      array << section.curriculum
    end
    @decks = @curriculums.map(&:decks).flatten
    @outstanding_decks = @decks.select { |deck| deck.attempts.where(user: @user).length != deck.cards.count }
    @completed_decks = @decks.select { |deck| deck.attempts.where(user: @user).length == deck.cards.count }
  end

  def takedeck
    authorize @user
    @deck = Deck.find(params[:deck])
    @attempt = Attempt.new
  end

  def decksummary
    authorize @user
    @deck = Deck.find(params[:deck])
    @correct_answers = @deck.attempts.where(user: current_user, response: "Correct")
    @wrong_answers = @deck.attempts.where(user: current_user, response: "Incorrect")
    @unsure_answers = @deck.attempts.where(user: current_user, response: "I don't know")
  end

  def deck_results
    @deck = Deck.find(params[:deck_id])
    @teacher = @deck.curriculum.user
    authorize @teacher
    @section = Section.find(params[:section_id])
    @attempts = Deck.find(params[:deck_id]).curriculum.sections.where(id: params[:section_id]).first.users.where(id: params[:id]).first.attempts
    @student = User.find(params[:id])
    @correct_answers = @deck.attempts.where(user: User.find(params[:id]), response: "Correct")
    @wrong_answers = @deck.attempts.where(user: User.find(params[:id]), response: "Incorrect")
    @unsure_answers = @deck.attempts.where(user: User.find(params[:id]), response: "I don't know")
  end

  def feed
    @feed_events = current_user.feed.paginate(page: params[:page])
    authorize  current_user

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/views/users/dashboard.html.erb
<div class="container">
  <h1>Welcome, <%= @user.first_name %>!</h1>

  <% if @outstanding_decks.count == 0 %>
  Looks like you've done all your work 💪
  <% end %>

  <% if @outstanding_decks.count > 0 %>
  You have <span style="color: #FAC70A;"><strong><%= @outstanding_decks.count %></strong></span> incomplete <%= "deck".pluralize(@outstanding_decks.count) %>.

  <div class="dashboard-deck-container">
    <h2>Outstanding decks</h2>
    <% @outstanding_decks.sort_by(&:due_date).each do |deck| %>
      <div class="deck-card">
        <div class="top-line">
          <p><i class="fas fa-book"></i> <%= deck.name %></p>
          <% if deck.due_date - Date.today() < 0 %>
            <p class="passed-due-date">Overdue: <%= deck.due_date.strftime("%b %d") %></p>
          <% elsif deck.due_date - Date.today() < 3 %>
            <p class="short-due-date">Due: <%= deck.due_date.strftime("%b %d") %></p>
          <% else %>
            <p>Due: <%= deck.due_date.strftime("%b %d") %></p>
          <% end %>
        </div>
        <div class="row help" style="margin-bottom: 8px;">
          <div class="col-8 px-0">
            <p class="deck-name"><%= deck.curriculum.name %></p>
          </div>
          <div class="col-4 px-0 text-right">
            <%= link_to "Finish now", takedeck_user_path(deck: deck, question: deck.attempts.where(user: @user).count || 0), class: "btn btn-yellow btn-finish" %>
          </div>
        </div>
        <div class="progress mt-3">
          <div class="progress-bar" role="progressbar" style="width: <%= deck.attempts.where(user: @user).count / deck.cards.count.to_f * 100 %>%" aria-valuenow="<%= deck.attempts.where(user: @user).count / deck.cards.count.to_f * 100 %>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>


  <% if @completed_decks.count > 0 %>
  <div class="dashboard-deck-container">
    <h2>Completed decks, nice job!</h2>
    <% @completed_decks.sort_by(&:due_date).reverse.each do |deck| %>
      <div class="deck-card">
        <div class="top-line">
          <p><i class="fas fa-book"></i> <%= deck.name %></p>
          <p class="completed-due-date">Completed</p>
        </div>
        <div class="row" style="margin-bottom: 8px;">
          <div class="col-9 px-0">
            <p class="deck-name"><%= deck.curriculum.name %></p>
          </div>
          <div class="col-3 px-0 text-right">
            <%= link_to "Review", decksummary_user_path(@user, deck: deck), class: "btn btn-grey btn-complete" %>
          </div>
        </div>
        <div class="progress mt-3">
          <div class="progress-bar" role="progressbar" style="width: <%= deck.attempts.where(user: @user).count / deck.cards.count.to_f * 100 %>%" aria-valuenow="<%= deck.attempts.where(user: @user).count / deck.cards.count.to_f * 100 %>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      </div>
    <% end %>
  </div>
  <% end %>
</div>

app/views/users/deck_results.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><span>Results for <%= @student.first_name %></span></h1>
      <h2><%= @deck.name %></h2>
    </div>
  </div>

  <div class="deck-score-container">
    <% unless @correct_answers.count == 0 %>
      <%= render 'shared/arc', color: 'green', percentage: (@correct_answers.count / @deck.cards.count.to_f) * 100,  size: 'medium', text: "Right" %>
    <% end %>
    <% unless @unsure_answers.count == 0 %>
      <%= render 'shared/arc', color: 'blue', percentage: (@unsure_answers.count / @deck.cards.count.to_f) * 100,  size: 'medium', text: "Unsure" %>
    <% end %>
    <% unless @wrong_answers.count == 0 %>
      <%= render 'shared/arc', color: 'red', percentage: (@wrong_answers.count / @deck.cards.count.to_f) * 100,  size: 'medium', text: "Wrong" %>
    <% end %>
  </div>

  <% unless @wrong_answers.count == 0 %>
    <% if @correct_answers.count == @deck.cards.count && @deck.cards.count > 1 %>
      <h2><%= @student.first_name %> had all <%= pluralize(@wrong_answers.count, 'question') %> wrong</h2>
    <% else %>
      <h2><%= @student.first_name %> had <%= pluralize(@wrong_answers.count, 'question') %> wrong</h2>
    <% end %>

    <% @wrong_answers.each do |wronganswer| %>
      <%= render 'shared/question-summary-card', responsestatus: wronganswer %>
    <% end %>
  <% end %>

  <% unless @unsure_answers.count == 0 %>
    <% if @unsure_answers.count == @deck.cards.count && @deck.cards.count > 1 %>
      <h2><%= @student.first_name %> was unsure about all <%= pluralize(@unsure_answers.count, 'question') %></h2>
    <% else %>
      <h2><%= @student.first_name %> was unsure about <%= pluralize(@unsure_answers.count, 'question') %></h2>
    <% end %>

    <% @unsure_answers.each do |unsureanswer| %>
      <%= render 'shared/question-summary-card', responsestatus: unsureanswer %>
    <% end %>
  <% end %>

  <% unless @correct_answers.count == 0 %>
    <% if @correct_answers.count == @deck.cards.count && @deck.cards.count > 1 %>
      <h2><%= @student.first_name %> had all <%= pluralize(@correct_answers.count, 'question') %> right</h2>
    <% else %>
      <h2><%= @student.first_name %> had <%= pluralize(@correct_answers.count, 'question') %> right</h2>
    <% end %>

    <% @correct_answers.each do |correctanswer| %>
      <%= render 'shared/question-summary-card', responsestatus: correctanswer %>
    <% end %>
  <% end %>

  <%= link_to "Back to section dashboard", section_deck_path(@section, @deck), class: "back-dashboard-link" %>

</div>

app/views/users/decksummary.html.erb
<div class="container">
  <canvas id="celebration"></canvas>

  <h1><span><%= @deck.name %></span></h1>

  <p>Great job, you've completed this deck! 👍</p>

  <div class="deck-score-container">
    <% unless @correct_answers.count == 0 %>
      <%= render 'shared/arc', color: 'green', percentage: (@correct_answers.count / @deck.cards.count.to_f) * 100,  size: 'medium', text: "Right" %>
    <% end %>
    <% unless @unsure_answers.count == 0 %>
      <%= render 'shared/arc', color: 'blue', percentage: (@unsure_answers.count / @deck.cards.count.to_f) * 100,  size: 'medium', text: "Unsure" %>
    <% end %>
    <% unless @wrong_answers.count == 0 %>
      <%= render 'shared/arc', color: 'red', percentage: (@wrong_answers.count / @deck.cards.count.to_f) * 100,  size: 'medium', text: "Wrong" %>
    <% end %>
  </div>

  <% unless @wrong_answers.count == 0 %>
    <% if @correct_answers.count == @deck.cards.count && @deck.cards.count > 1 %>
      <h2>You had all <%= pluralize(@wrong_answers.count, 'question') %> wrong</h2>
    <% else %>
      <h2>You had <%= pluralize(@wrong_answers.count, 'question') %> wrong</h2>
    <% end %>

    <% @wrong_answers.each do |wronganswer| %>
      <%= render 'shared/question-summary-card', responsestatus: wronganswer %>
    <% end %>
  <% end %>

  <% unless @unsure_answers.count == 0 %>
    <% if @unsure_answers.count == @deck.cards.count && @deck.cards.count > 1 %>
      <h2>You were unsure about all <%= pluralize(@unsure_answers.count, 'question') %></h2>
    <% else %>
      <h2>You were unsure about <%= pluralize(@unsure_answers.count, 'question') %></h2>
    <% end %>

    <% @unsure_answers.each do |unsureanswer| %>
      <%= render 'shared/question-summary-card', responsestatus: unsureanswer %>
    <% end %>
  <% end %>

  <% unless @correct_answers.count == 0 %>
    <% if @correct_answers.count == @deck.cards.count && @deck.cards.count > 1 %>
      <h2>You had all <%= pluralize(@correct_answers.count, 'question') %> right</h2>
    <% else %>
      <h2>You had <%= pluralize(@correct_answers.count, 'question') %> right</h2>
    <% end %>

    <% @correct_answers.each do |correctanswer| %>
      <%= render 'shared/question-summary-card', responsestatus: correctanswer %>
    <% end %>
  <% end %>

  <%= link_to "Back to dashboard", dashboard_user_path(@user), class: "back-dashboard-link" %>

</div>

app/views/users/feed.html.erb
<div class="container">
  <div class="row ">
    <div class="col-sm-12">
      <div class="row my-3">
        <div class="col-sm-12">
          <h1><span>My feed</span></h1>
          <h2>Welcome, <%= current_user.first_name %></h2>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
            <%= render @feed_events %>
            <div class="pagination-container">
              <%= will_paginate @feed_events %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/feed.js.erb
$('#my-feed').append('<%= j render @feed_eventd %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @feed_events %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="sections">
    <div class="row mb-3">
      <div class="col-md-6">
        <h1><span><%= @user.first_name %> <%= @user.last_name %></span></h1>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <% if @user.photo.file %>
          <%= cl_image_tag(@user.photo, class: "avatar-large") %>
        <% else %>
          <%= cl_image_tag("ptvra7owhsunxrse9zut.png", class: "avatar-large") %>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h2>Shared decks</h2>
          <% if @shared_decks.empty? %>
            <p><%= @user.first_name %> hasn't shared any decks</p>
          <% else %>
            <% @shared_decks.each do |deck| %>
              <%= deck.name %>
            <% end %>
          <% end %>
      </div>
    </div>
    <% if @user == current_user %>
      <div class="row">
        <div class="col-md-6">
          <h2>My decks</h2>
          <% if @user_decks.empty? %>
            <p>You don't have any decks</p>
          <% else %>
            <% @user_decks.each do |deck| %>
              <%= deck.name %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/takedeck.html.erb
<div class="container question-container">
  <h1><span><%= @deck.name %></span></h1>
  <div class="question-card transform">
    <!-- <h2>Question <%= params[:question].to_i + 1 %></h2> -->
    <p><%= @deck.cards[params[:question].to_i].question %></p>
    <div class="choice-container">
      <%= link_to @deck.cards[params[:question].to_i || 0].wrong_answer, attempts_path(@attempt, response: "Incorrect", card_id: @deck.cards[params[:question].to_i], deck_id: @deck, question: params[:question].to_i), method: :post, class: "btn-answer left" %>
      <%= link_to "Not sure", attempts_path(@attempt, response: "I don't know", card_id: @deck.cards[params[:question].to_i], deck_id: @deck, question: params[:question].to_i), method: :post, class: "btn-answer help" %>
      <%= link_to @deck.cards[params[:question].to_i || 0].correct_answer, attempts_path(@attempt, response: "Correct", card_id: @deck.cards[params[:question].to_i], deck_id: @deck, question: params[:question].to_i), method: :post, class: "btn-answer right" %>
    </div>
  </div>

  <%= image_tag("swipe-hand-touch-finger.png", class: "swipe-helper") %>

  <div class="progress-text">Question <%= @deck.attempts.where(user: @user).count + 1 %> / <%= @deck.cards.count %></div>
  <div class="progress mt-3">
    <div class="progress-bar" role="progressbar" style="width: <%= @deck.attempts.where(user: @user).count / @deck.cards.count.to_f * 100 %>%" aria-valuenow="<%= @deck.attempts.where(user: @user).count / @deck.cards.count.to_f * 100 %>" aria-valuemin="0" aria-valuemax="100"></div>
  </div>

</div>