config/routes.rb
Rails.application.routes.draw do
  get 'resources/new'
  get 'resources/edit'
  get 'cards/new'
  get 'cards/edit'
  devise_for :users

  root to: 'passthrough#index'

  get 'home', to: 'pages#home'

  resources :curriculums, only:[:show, :index] do
    resources :decks, only:[:index, :edit, :update, :new, :create] do
      resources :cards, only:[:edit, :update, :new, :create, :index, :show]
      resources :resources, only: [:new, :create, :edit, :update]
    end
  end

  resources :users, only: [] do
    member do
      get 'dashboard'
      get 'takedeck'
      get 'decksummary'
    end
  end
  resources :attempts, only: [:create]

  resources :sections, only: :show do
    resources :decks, only: :show do
      resources :students, only: :show
        resources :users, only: [] do
          member do
            get 'deck_results'
          end
        end
    end
  end

  get 'feed', to: 'users#feed'

  resources :todo_items, only: [:create, :index] do
    member do
      get 'mark_complete'
    end
  end

end

app/views/shared/_arc.html.erb
<svg viewBox="0 0 36 36" class="circular-chart circle-<%= size %>">
  <path class="circle circle-light-grey" d="M18 2.0845
      a 15.915507752443826 15.915507752443826 0 0 1 0 31.831015504887652
      a 15.915507752443826 15.915507752443826 0 0 1 0 -31.831015504887652" stroke-dasharray="100, 100"></path>
  <path class="circle circle-<%= color %>" d="M18 2.0845
      a 15.915507752443826 15.915507752443826 0 0 1 0 31.831015504887652
      a 15.915507752443826 15.915507752443826 0 0 1 0 -31.831015504887652" stroke-dasharray="<%= percentage.round %>, 100"></path>

  <% if size == 'medium' %>
    <text x="50%" y ="50%" style="font-size:6px" dominant-baseline="middle" text-anchor="middle" class="circle-label"><%= text %></text>
  <% elsif size == 'large' %>
    <text x="50%" y ="45%" dominant-baseline="middle" text-anchor="middle" class="circle-label"><%= text %></text>
    <text x="50%" y ="65%" dominant-baseline="middle" text-anchor="middle" class="circle-label"><%= percentage.round %>%</text>
  <% end %>
</svg>

app/views/shared/_cards.html.erb
<div class="container">
	<h2>my courses</h2>
		<div class="cards">
			<div class="card-rating">
				<div class="card">
					<div class="background-image" style="background-image: url(https://picsum.photos/400)">
					</div>

					<div class="card-bottom">
						<div class="description">
							<h2> Abstract Design</h2>
							<p> We are going to learn how to use acrylic pain and dsfdf</p>
						</div>

						<div class="avatars">
							<img src="https://www.gannett-cdn.com/presto/2018/11/02/PMOR/b8cfb6be-d5d7-4c36-8f2e-16acb2d38eaf-MissingMorris1.jpg?width=534&height=712&fit=bounds&auto=webp" class="img-circle">
							<img src="https://www.gannett-cdn.com/presto/2018/11/02/PMOR/b8cfb6be-d5d7-4c36-8f2e-16acb2d38eaf-MissingMorris1.jpg?width=534&height=712&fit=bounds&auto=webp" class="img-circle">
						</div>
					</div>

				</div>

				<div class="p-bar">
					<div class="p-bar-margin">
						<div class="progress" style="height: 10px">
						  <div class="progress-bar progress-bar-striped bg-success progress-bar-margin" role="progressbar" style="width: 20%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
</div>

app/views/shared/_deck-completion-card.html.erb
<div class="container">
	<div class="deck-completion-card">
		<div class="image-and-name">
			<div class="dcc-img" class="background-image" style="background-image: url(https://picsum.photos/400);"></div>
			<p>Deck name</p>
		</div>
		<div class="progress-holder">
			<div class="progress" style="height: 10px;">
			   <div class="progress-bar progress-bar-striped bg-success progress-bar-margin" role="progressbar" style="width: 50%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
			</div>
		</div>
	</div>	
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_left-nav.html.erb
<div class="left-nav">
  <div class="menu-list">
    <h2>Dashboard</h2>
    <div class="menu-item selected">
      <%= link_to curriculums_path do %>
        <i class="fas fa-user-graduate mr-2"></i>My Sections
      <% end %>
    </div>
    <div class="menu-item">
      <a href="#"><i class="fas fa-book mr-2"></i>My Curriculums </a>
    </div>
  </div>
  <br>
  <br>
  <div class="curriculum-list curriculums" hidden>
    <h2>Curriculums</h2>
    <% @curriculums.each do |curriculum| %>
      <h4> <%= curriculum.name %> </h4>
      <% curriculum.decks.each do |deck| %>
        <%= link_to "<i class='fas fa-angle-double-right'></i> #{deck.name}".html_safe, curriculum_deck_cards_path(curriculum, deck), class: "decks-list-item"%>
        <% end %>
    <% end %>
  </div>


  <div class="section-list sections">
    <h2>Sections</h2>
    <% @curriculums.each_with_index do |curriculum , index| %>
       <a data-toggle="collapse" href="#collapseLeftNav<%= index %>" role="button" aria-expanded="false" aria-controls="collapseExample" style="font-size:16px;"> <i class="fas fa-caret-down"></i> <%= curriculum.name %> </a>

       <div class="collapse" id="collapseLeftNav<%= index %>">
        <% curriculum.sections.each do |section| %>
          <%= link_to "<i class='fas fa-angle-double-right'></i> Section #{section.name}".html_safe, section_path(section), class: "sections-list-item"%>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <% if current_user.is_teacher %>
      <%= link_to image_tag("YellowClick.png"), curriculums_path %>
    <% else %>
      <%= link_to image_tag("YellowClick.png"), dashboard_user_path(current_user) %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="dropdown" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

      <%= cl_image_tag(current_user.photo.url,  class: "avatar av-img dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <% if current_user.is_teacher %>
              <%= link_to "My Feed", feed_path, class: "dropdown-item" %>
            <% end %>
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
<% else %>
  <div class="navbar navbartransparent">
    <a href=<%= root_path %>><img src=<%=asset_path "BlackClick.png"%> alt=""></a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="button-holder">
      <% unless params[:controller] == 'devise/registrations' && params[:action] == 'new' %>
        <div class="btn btn-yellow btn-homepage-navbar">
          <%= link_to "Sign Up", new_user_registration_path %>
        </div>
      <% end %>
      <% unless params[:controller] == 'devise/sessions' && params[:action] == 'new' %>
        <button type="button" class="btn btn-grey btn-homepage-navbar" data-toggle="modal" data-target="#loginModal">Log In</button>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_progress_bar.html.erb
 <div class="bar green" data-toggle="tooltip" title="Correct" style="width:<%= correct %>%"></div>
 <div class="bar red" data-toggle="tooltip" title="Incorrect" style="width:<%= incorrect %>%"></div>
 <div class="bar" data-toggle="tooltip" title="Unsure" style="width:<%= 100 - correct - incorrect %>%"></div>

app/views/shared/_question-summary-card.erb
<div class="question-summary-card">
  <div class="short-answer">
    <p>"<em><%= responsestatus.card.question.truncate(100) %></em>"</p>
    <p>The correct answer was <strong><%= responsestatus.card.correct_answer.downcase %></strong></p>
    <p class="expand-card btn btn-yellow btn-details">Learn more</p>
  </div>
  <div class="long-answer">
    <p>"<em><%= responsestatus.card.question %></em>"</p>
    <p>The correct answer was <strong><%= responsestatus.card.correct_answer.downcase %></strong></p>
    <% unless responsestatus.card.resource.nil? %>
      <p><%= responsestatus.card.resource.text %></p>
      <% if responsestatus.card.resource.name.downcase.include?("video") %>
        <% video_id = responsestatus.card.resource.url.match(/^.*(youtu\.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/) %>
        <div class="video-container">
          <iframe src="http://www.youtube.com/embed/<%= video_id[2] %>"></iframe>
        </div>
      <% elsif responsestatus.card.resource.url.match(/.jpg|.png|.gif/) %>
      <%= image_tag responsestatus.card.resource.url, class: "resource-image" %>
      <% elsif responsestatus.card.resource.url %>
        <p><%= link_to '<i class="fas fa-link"></i> Click here to open'.html_safe, responsestatus.card.resource.url, target: :_blank %></p>
      <% end %>
    <% end %>
    <p class="collapse-card expand-card btn btn-yellow btn-details">Show less</p>
  </div>
</div>

app/views/shared/_student-list-card.html.erb
<div class="container">
	<div class="student-list-card ">
		<div class="student-number-and-icon">
			<p>23 students</p>
			<p ><i class="fas fa-pencil-alt"></i></p>
		</div>
		<div class="students">
			<div class="student-info border-bottom">
				<div class="avatar-small" style="background-image: url(https://picsum.photos/400)">
				</div>
				<p>Jonny Gates</p>
			</div>
		</div>
	</div>
</div>