config/routes.rb
Rails.application.routes.draw do
  get 'resources/new'
  get 'resources/edit'
  get 'cards/new'
  get 'cards/edit'
  devise_for :users

  root to: 'passthrough#index'

  get 'home', to: 'pages#home'

  resources :curriculums, only:[:show, :index] do
    resources :decks, only:[:index, :edit, :update, :new, :create] do
      resources :cards, only:[:edit, :update, :new, :create, :index, :show]
      resources :resources, only: [:new, :create, :edit, :update]
    end
  end

  resources :users, only: [] do
    member do
      get 'dashboard'
      get 'takedeck'
      get 'decksummary'
    end
  end
  resources :attempts, only: [:create]

  resources :sections, only: :show do
    resources :decks, only: :show do
      resources :students, only: :show
        resources :users, only: [] do
          member do
            get 'deck_results'
          end
        end
    end
  end

  get 'feed', to: 'users#feed'

  resources :todo_items, only: [:create, :index] do
    member do
      get 'mark_complete'
    end
  end

end

app/models/card.rb
class Card < ApplicationRecord
  attr_accessor :new_resource
  has_many :attempts
  belongs_to :deck
  belongs_to :resource, optional: true
  validates :question, :correct_answer, :wrong_answer, presence: true

  attr_accessor :resource_name, :resource_url, :resource_text
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:edit]
  before_action :deck_resources, only: [:index, :new, :edit]

  def index
    @cards = policy_scope(Card).where(deck: Deck.find(params[:deck_id]))
    @deck = Deck.find(params[:deck_id])
    @curriculum = Curriculum.find(params[:curriculum_id])
    @card = Card.new
    @resource = Resource.new
  end

  def new
    @card = Card.new
    @card.deck = Deck.find(params[:deck_id])
    authorize @card
    @deck = @card.deck
    @curriculum = @deck.curriculum
  end

  def create
    @card = Card.new(card_params)
    @card.deck = Deck.find(params[:deck_id])
    @deck = @card.deck
    @curriculum = @deck.curriculum
    if !params[:card][:resource].empty?
      @card.resource = Resource.find(params[:card][:resource])
    elsif params[:card][:resource_name] && params[:card][:resource_text] && params[:card][:resource_url]
      resource = Resource.new(name: params[:card][:resource_name], text: params[:card][:resource_text], url: params[:card][:resource_url] )
      if resource.save
        @card.resource = resource
      end
    end
    authorize @card
    if @card.save
      flash[:notice] = "Card created"
      redirect_to curriculum_deck_cards_path(@curriculum, @deck)
    else
      flash[:notice] = "Card not created"
      redirect_to curriculum_deck_cards_path(@curriculum, @deck)
    end
  end

  def edit
    authorize @card
    @deck = @card.deck
    @curriculum = @deck.curriculum
  end

  def update
    @card = Card.find(params[:id])
    @card.update(card_params)
    @card.resource = @resource
    @card.save
    authorize @card
    @deck = @card.deck
    @curriculum = @deck.curriculum
    if @card.save
      redirect_to curriculum_deck_cards_path(@curriculum, @deck)
    else
      render :edit
    end
  end

  private

  def set_card
    @card = Card.find(params[:id])
  end

  def card_params
    params.require(:card).permit(:name, :question, :correct_answer, :wrong_answer)
  end

  def deck_resources
    resources = []
    Deck.find(params[:deck_id]).cards.each do |card|
      if card.resource
        resources << card.resource
      end
    end
    @resources = resources.uniq
  end
end

app/views/cards/_new_resource.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2>New Resource</h2>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@curriculum, @deck, @resource], :method => :post do |f| %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :text %>
        <%= f.input :url %>
        <%= f.input :card, collection: cards, label_method: :question %>
      </div>
      <div class="form-actions">
        <%= f.submit "Create Resource", class: "btn btn-yellow new-card" %>
      </div>
    <% end %>
      </div>
    </div>
  </div>

app/views/cards/create.js.erb
//Show add new resource form if selected whan making new card
const checkbox = document.querySelector("#new_resource");
const fakeButton = document.querySelector("#fake-button");
const modal = document.querySelector(".modal-header");





console.log('respond');

app/views/cards/edit.html.erb
<div class="container">
  <h1> <span> Edit this Card </span></h1>
  <div class="row">
    <!-- update the file path in line 5  -->
    <%= simple_form_for [@curriculum, @deck, @card], :method => :patch do |f| %>
      <div class="col-12 col-md-6">
        <%= f.input :question %>
      </div>
      <div class="col-12 col-md-6">
        <%= f.input :correct_answer %>
      </div>
      <div class="col-12 col-md-6">
        <%= f.input :wrong_answer %>
      </div>
      <div class="col-12 col-md-6">
        <%= f.input :resource, collection: @resources, label_method: :name%>
      </div>
      <div class="col-md-12">
        <%= f.submit "Update Card" %>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/index.html.erb
  <div class="container">
    <div class="col-sm-12">
      <h1><span> <%= @deck.name %></span><%= link_to '<i class="fas fa-pen heading-edit"></i>'.html_safe, edit_curriculum_deck_path(@curriculum, @deck) %> </h1>
      <button type="button" class="btn btn-yellow" data-toggle="modal" data-target="#myResourceModal">+ New Resource</button>
    </div>
    <div class="flashcard-grid column col-lg-3 col-6">
      <a data-toggle="modal" href="#myModal">
      <div class="flashcard flashcard-new">
        <div class="text d-flex align-items-center justify-content-center">
          <i class="fas fa-plus-circle"></i>
        </div>
        <div class="resources">
          <div class="resources-text">
          </div>
        </div>
      </div>
      </a>
      <% @deck.cards.each do |card| %>
        <div class="flashcard">
          <div class="text">
            <%= truncate(card.question, length: 100) %>
          </div>
          <div class="resources">
            <div class="resources-text">
              <% if card.resource %>
                <%= truncate(card.resource.name, length: 30) %>
              <% end %>
            </div>
            <div class="edit-link-icon">
              <%= link_to '<i class="fas fa-pen"></i>'.html_safe, edit_curriculum_deck_card_path(@curriculum, @deck, card) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<!-- New card modal content-->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2>New Card</h2>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@curriculum, @deck, @card], :method => :post do |f| %>
      <div class="form-inputs">
        <%= f.input :question%>
        <%= f.input :correct_answer %>
        <%= f.input :wrong_answer %>
        <%= f.input :resource, collection: @resources%>
        <a  data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
          Add new resource?
        </a>
        <div class="collapse" id="collapseExample">
          <p class="add-resource">
              <%= f.input :resource_name %>
              <%= f.input :resource_text %>
              <%= f.input :resource_url %>
          </p>
        </div>

      </div>
      <div class="form-actions">
        <%= f.submit "Create Card", class: "btn btn-yellow" %>
      </div>
    <% end %>
      </div>
    </div>
  </div>
</div>



<!-- New resource modal content-->
<div id="myResourceModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h2>New Resource</h2>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@curriculum, @deck, @resource], :method => :post do |f| %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :text %>
        <%= f.input :url %>
        <div class="media-preview"></div>
        <%= f.input :card, collection: @cards, label_method: :question %>
      </div>
      <div class="form-actions">
        <%= f.submit "Create Resource", class: "btn btn-yellow new-card" %>
      </div>
    <% end %>

      </div>
    </div>
  </div>
</div>