config/routes.rb
Rails.application.routes.draw do
  get 'resources/new'
  get 'resources/edit'
  get 'cards/new'
  get 'cards/edit'
  devise_for :users

  root to: 'passthrough#index'

  get 'home', to: 'pages#home'

  resources :curriculums, only:[:show, :index] do
    resources :decks, only:[:index, :edit, :update, :new, :create] do
      resources :cards, only:[:edit, :update, :new, :create, :index, :show]
      resources :resources, only: [:new, :create, :edit, :update]
    end
  end

  resources :users, only: [] do
    member do
      get 'dashboard'
      get 'takedeck'
      get 'decksummary'
    end
  end
  resources :attempts, only: [:create]

  resources :sections, only: :show do
    resources :decks, only: :show do
      resources :students, only: :show
        resources :users, only: [] do
          member do
            get 'deck_results'
          end
        end
    end
  end

  get 'feed', to: 'users#feed'

  resources :todo_items, only: [:create, :index] do
    member do
      get 'mark_complete'
    end
  end

end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards
  has_many :attempts, through: :cards
  belongs_to :curriculum

  validates :name, presence: true

  def last_attempt(section)
    attempts = deck_attempts(self, section)
    attempts.sort_by { |attempt| attempt.created_at }.last.created_at
  end

  def deck_results(section)
    attempts = deck_attempts(self, section)
    total = attempts.count.to_f
    {
      correct: (attempts.count { |attempt| attempt.response == "Correct" } / total) * 100,
      incorrect: (attempts.count { |attempt| attempt.response == "Incorrect" } / total) * 100,
      unsure: (attempts.count { |attempt| attempt.response == "I don't know" } / total) * 100
    }
  end

  private

  def deck_attempts(deck, section)
    attempts = []
    deck.curriculum.sections.where(id: section.id).first.users.each do |user|
      user.attempts.each { |attempt| attempts << attempt if attempt.card.deck == deck }
    end
    attempts
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit]
    skip_before_action :authenticate_user!, only: [:edit]

  def index
    @decks = policy_scope(Deck).joins(:curriculum).where("decks.curriculum_id = #{params[:curriculum_id]}")
  end

  def show
    @section = Section.find(params[:section_id])
    @results_by_card = {}
    @results = @deck.deck_results(@section)
    attempts = @section.users.map { |user| user.attempts.select { |attempt| attempt.card.deck == @deck } }
    @last_attempt = @deck.last_attempt(@section)
    @deck.cards.each do |card|
      @results_by_card[card.id] = {card: card, results: { attempts: 0, correct: 0, incorrect: 0, unsure: 0 } }
    end
    attempts.each do |collection|
      collection.each do |attempt|
        @results_by_card[attempt.card.id][:results][:attempts] += 1
        case attempt.response
        when "Correct"
          # @results[:correct] += 1
          @results_by_card[attempt.card.id][:results][:correct] += 1
        when "Incorrect"
          # @results[:incorrect] += 1
          @results_by_card[attempt.card.id][:results][:incorrect] += 1
        when "I don't know"
          # @results[:unsure] += 1
          @results_by_card[attempt.card.id][:results][:unsure] += 1
        end
      end
    end
    @results_by_card.sort_by { |card| card[1][:results][:incomplete]}
    authorize @deck
  end

  def new
    @deck = Deck.new
    @deck.curriculum = Curriculum.find(params[:curriculum_id])
    @curriculum = @deck.curriculum
    authorize @deck
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.curriculum = Curriculum.find(params[:curriculum_id])
    @curriculum = @deck.curriculum
    if @deck.save
      authorize @deck
      redirect_to curriculum_deck_cards_path(@curriculum, @deck)
    else
      render :new
    end
  end

  def edit
    authorize @deck
    @curriculum = @deck.curriculum
  end

  def update
    @deck = Deck.update(params[:id], deck_params)
    authorize @deck
    @curriculum = @deck.curriculum
    if @deck.save
      redirect_to curriculum_deck_cards_path(@curriculum, @deck)
    else
      render :edit
    end
  end

  private

  def set_deck
    @deck = Deck.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name)
  end

end

app/views/decks/_form.html.erb
<div class="row">
  <%= simple_form_for [@curriculum, @deck], :method => :patch do |f| %>
    <div class="col-12 col-md-6">
      <%= f.input :name %>
    </div>
    <div class="col-md-12">
      <%= f.submit "Submit changes"%>
    </div>
  <% end %>
</div>

app/views/decks/edit.html.erb
<div class="container">
  <h1><span> Edit <%= @deck.name %></span></h1>
  <div class="edit-deck">
    <%= render 'form', deck: @deck %>
  </div>
</div>

app/views/decks/index.html.erb
<% flash.error = "Delete page if not required!" %>
<div class="main">
  <div class="container">
    <h1><span>Section <%= Section.find(params[:section_id]).name %></span></h1>
    <h2> <i class="fas fa-book"></i><%= Curriculum.find(params[:curriculum_id]).name %> </h2>
    <h3>Outstanding Decks</h3>
    <% @decks.each do |deck| %>
      <% if deck.due_date > Date.today %>
        <%= link_to curriculum_section_deck_path(params[:curriculum_id], params[:section_id], deck.id) do %>
          <div class="container deck-card">
            <p> <%= deck.name %> </p>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <h3>Completed Decks</h3>
    <% @decks.each do |deck| %>
      <% if deck.due_date < Date.today %>
        <%= link_to curriculum_section_deck_path(params[:curriculum_id], params[:section_id], deck.id) do %>
          <div class="container deck-card">
            <p> <%= deck.name %> </p>
          </div>
        <% end %>
      <% end %>
    <% end %>

    <h3>Students</h3>
    <h4><%= Section.find(params[:section_id]).users.length %> students</h4>
    <div class="container student-list">
      <% Section.find(params[:section_id]).users.each do |user| %>
        <% unless user.is_teacher %>
          <p><%= link_to "#{user.first_name} #{user.last_name}", root_path %></p>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/decks/new.html.erb
<div class="container">
  <h1><span> Add a Deck </span></h1>
  <div class="row">
    <%= simple_form_for [@curriculum, @deck], :method => :post do |f| %>
      <div class="col-12 col-md-6">
        <%= f.input :name %>
      </div>
      <div class="col-md-12">
        <%= f.submit "Create Deck"%>
      </div>
    <% end %>
  </div>
</div>

app/views/decks/show.html.erb
  <div class="container">
      <div class="row mb-3">
        <div class="col-sm-12">


          <div class="row mb-3">
            <h1 style="width: 100%"><span><%= @deck.name %></span></h1>
            <h2>Section <%= @section.name %></h2>
          </div>

          <div class="row">
            <div class="col-sm-12 col-md-4">
              <%= render 'shared/arc', color: 'green', percentage: @results[:correct] , text: 'Correct', size: 'large' %>
            </div>
            <div class="col-sm-12 col-md-4">
              <%= render 'shared/arc', color: 'red', percentage: @results[:incorrect] , text: 'Incorrect', size: 'large' %>
            </div>
            <div class="col-sm-12 col-md-4">
              <%= render 'shared/arc', color: 'grey', percentage: @results[:unsure] , text: 'Unsure', size: 'large' %>
            </div>
          </div>

          <div class="row mb-3 py-9">
            <div class="col-sm-12">
              <div class="deck-info d-flex align-items-center">
                <div class="deck-data">
                  <p><i class="far fa-calendar-plus"></i> <strong>Last played</strong> <%= time_ago_in_words(@last_attempt) %> ago</p>
                  <p><i class="fas fa-layer-group"></i> <strong>Cards</strong> <%= @deck.cards.count %></p>
                </div>
                <%= link_to "Edit deck", curriculum_deck_cards_path(@deck.curriculum, @deck), class: 'btn btn-yellow' %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-12 col-md-6">
              <div class="section">
                <% @section.users.each do |student| %>
                <div class="student-list-item">
                  <div class="student-info">
                      <%= cl_image_tag(student.photo.url, class: "avatar-small") %>
                    <div class="student-name">
                        <p><%= link_to (student.first_name + " " + student.last_name), deck_results_section_deck_user_path(@section, @deck, student) %></p>
                        <div class="attempts-bar">
                    <% student.deck_attempts(@deck).each do |attempt| %>
                      <% if attempt.response == "Correct" %>
                        <div class="attempt attempt-green" data-toggle="tooltip" title="<%= attempt.card.question %>"></div>
                      <% elsif attempt.response == "Incorrect" %>
                        <div class="attempt attempt-red" data-toggle="tooltip" title="<%= attempt.card.question %>"></div>
                      <% else %>
                        <div class="attempt attempt-grey" data-toggle="tooltip" title="<%= attempt.card.question %>"></div>
                      <% end %>
                    <% end %>
                  </div>
                    </div>

                  </div>



                </div>
                <% end %>

              </div>
            </div>
            <div class="col-sm-12 col-md-6">
              <div class="section">
                <% @results_by_card.each do |result| %>
                  <div class="student-info">
                    <div class="student-list-content">
                      <div class="student-name">
                        <p class="question-text"><%= truncate(result[1][:card].question, length: 200) %></p>
                        <% attempts = result[1][:results][:attempts].to_f %>
                        <% correct = result[1][:results][:correct] == 0 ? 0 : (result[1][:results][:correct] / attempts) * 100 %>
                        <% incorrect = result[1][:results][:incorrect] == 0 ? 0 : (result[1][:results][:incorrect] / attempts) * 100 %>
                        <% unsure = result[1][:results][:unsure] == 0 ? 0 : (result[1][:results][:unsure] / attempts) * 100 %>
                      </div>

                        <%= render 'shared/arc', color: 'green', percentage: correct,  size: 'small' %>


                        <%= render 'shared/arc', color: 'red', percentage: incorrect,  size: 'small' %>


                        <%= render 'shared/arc', color: 'grey', percentage: unsure,  size: 'small' %>

                    </div>
                  </div>
                <% end %>
              </div>
            </div>

          </div>
        </div>
      </div>
  </div>